<?php
    if(!empty($_GET['action'])){ 
        if(!empty($_GET['eventAccept'])){
            require("calender_event_accept.php");
        }
        if(!empty($_GET['eventDecline'])){
            require("calender_event_decline.php");
        }
    }
?>