<?php
    if(isset($_GET['eventHandle'])){ 
        if(isset($_GET['eventAccept'])){
            require("calender_event_accept.php");
        }
        if(isset($_GET['eventDecline'])){
            require("calender_event_decline.php");
        }
    }
?>